#pragma config(Sensor, S1,     sen1,           sensorEV3_Color, modeEV3Color_RGB_Raw)
#pragma config(Sensor, S2,     sen2,           sensorEV3_Color, modeEV3Color_RGB_Raw)
#pragma config(Sensor, S3,     sen3,           sensorEV3_Color, modeEV3Color_RGB_Raw)
#pragma config(Motor,  motorA,          motA,          tmotorEV3_Large, openLoop, encoder)
#pragma config(Motor,  motorB,          motB,          tmotorEV3_Large, openLoop, encoder)
#pragma config(Motor,  motorC,          motC,          tmotorEV3_Large, openLoop, encoder)
#pragma config(Motor,  motorD,          motD,          tmotorEV3_Large, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "../include/PID_c_motors.c"
#include "../include/motion.c"
#include "../include/sen_for_colors.c"
#include "../include/motion_with_sensors.c"
#include "../include/PID_c_manip.c"

task main (){
	// define everything
	setSoundVolume(0);
	checkBat();
	clearTimer(T3);
	defStructures();
	setMotorBrakeMode(motB, motorCoast);
	setMotorBrakeMode(motC, motorCoast);
	startTask(PIDEngineMot);
	//startTask(keepBMoving);
	//startTask(keepCMoving);

	SenRGBVals nothing;
	SenRGBVals white;

	nothing.R = 0;
	nothing.G = 0;
	nothing.B = 0;

	white.R = 100;
	white.G = 100;
	white.B = 100;

	int inPtrs[2] = {(int) &nothing, (int) &white};
	int lenInPtrs = 2;

	int *resPtrs = startReadRowOfObjectsRGB(inPtrs, lenInPtrs, sen3, &SEN3_CALIBRATION);
	waitForButtonPress();
	stopTask(readRowOfObjectsRGB);
	eraseDisplay();
	for (int i = 0; i < 10; i++){
		if (resPtrs[i] == &nothing){
			displayTextLine(i, "nothing");
		}
		else if (resPtrs[i] == &white){
			displayTextLine(i, "white");
		}
		else{
			displayTextLine(i, "%d %d %d", resPtrs[i], &nothing, &white);
		}
	}
	sleep(1000);
	flushButtonMessages();
	waitForButtonPress();
}
