#define DEB_DISPLAY_CALIBRATED_RGB_SEN1 0
#define DEB_DISPLAY_CALIBRATED_RGB_SEN2 0
#define DEB_DISPLAY_CALIBRATED_RGB_SEN3 0
#define DEB_DISPLAY_CALIBRATED_RGB_SEN4 0

#define DEB_DISPLAY_MEAN_CALIBRATED_RGB_SEN1 0
#define DEB_DISPLAY_MEAN_CALIBRATED_RGB_SEN2 0
#define DEB_DISPLAY_MEAN_CALIBRATED_RGB_SEN3 0
#define DEB_DISPLAY_MEAN_CALIBRATED_RGB_SEN4 0

#define DEB_DISPLAY_CALIBRATON_VALUES 0

#define WRITE_DATA_IN_FILE 0

#define RUN_ONLY_TEST_FUNCTION 0