#define DEB_DISPLAY_CALIBRATED_RGB_SEN1 0
#define DEB_DISPLAY_CALIBRATED_RGB_SEN2 0
#define DEB_DISPLAY_CALIBRATED_RGB_SEN3 0
#define DEB_DISPLAY_CALIBRATED_RGB_SEN4 0

#define DEB_DISPLAY_MEAN_CALIBRATED_RGB_SEN1 0
#define DEB_DISPLAY_MEAN_CALIBRATED_RGB_SEN2 0
#define DEB_DISPLAY_MEAN_CALIBRATED_RGB_SEN3 0
#define DEB_DISPLAY_MEAN_CALIBRATED_RGB_SEN4 0

#define DEB_DISPLAY_CALIBRATON_VALUES 0
#define DEB_CALIBRATE_CUBES_1PART 0
#define DEB_CALIBRATE_CUBES_2PART 0

#define WRITE_DATA_IN_FILE 0

#define ONLY_SHOW_VOLTAGE 0
#define RUN_ONLY_TEST_FUNCTION 1
#define TEST_MOTOR_CALIBRATION 0

#define SLEEP_ON_FIRST_TAKE_BIG_SHIP 0
#define SLEEP_ON_CUBES 0
#define SLEEP_ON_READ_CUBE4 0